{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(pizzasSold_total[1m])", "legendFormat": "Pizzas Sold" },
    { "expr": "rate(pizzaFailure_total[1m])", "legendFormat": "Purchase Failures" }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(revenue_total[1m])", "legendFormat": "Revenue" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "request_latency", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Make Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "makePizza_latency", "legendFormat": "Pizza Latency" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(request_total{method=\"all\"}[1m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(request_total{method=\"get\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_total{method=\"post\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(request_total{method=\"delete\"}[1m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Auth Attempts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "rate(authentication_failed[1m])",
     "legendFormat": "Failures"
    },
    {
     "expr": "rate(authentication_successful[1m])",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 16 },
   "targets": [
    { "expr": "activeUsers_total", "legendFormat": "Active Users" }
   ]
  },
  {
   "title": "System Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu", "legendFormat": "__auto" }
   ]
  }
 ]
}